# Generated by Django 4.2.2 on 2023-06-08 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pay_from', models.CharField(max_length=50)),
                ('sum_expend_for_delivery', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_of_expend', models.CharField(max_length=100)),
                ('sum_of_month_expend', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MethodPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_method', models.CharField(max_length=100)),
                ('percent_method', models.DecimalField(decimal_places=2, max_digits=2)),
                ('income_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='main.income')),
            ],
        ),
    ]
