# Generated by Django 4.2.2 on 2023-06-08 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='income',
            name='pay_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Partners', to='main.partners'),
        ),
    ]
