# Generated by Django 4.2.2 on 2023-06-08 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_partners_alter_income_pay_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='methodpayment',
            name='income_id',
        ),
        migrations.AddField(
            model_name='income',
            name='method_payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.methodpayment'),
        ),
        migrations.AddField(
            model_name='income',
            name='real_date_payment',
            field=models.DateField(blank=True, null=True),
        ),
    ]
