# Generated by Django 4.2.2 on 2023-06-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_methodpayment_income_id_income_method_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodpayment',
            name='percent_method',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
