# Generated by Django 4.2.1 on 2023-05-29 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phones',
            name='phone',
        ),
    ]
