# Generated by Django 4.2.1 on 2023-05-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_phones_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='phones',
            name='color',
            field=models.CharField(max_length=40),
        ),
    ]
